apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: pickleman
    cluster: pickleman
    detail: pickle
    load-balancer-pickleman: "true"
  name: pickleman-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickleman
      cluster: pickleman
      detail: pickle
      load-balancer-pickleman: "true"
  template:
    metadata:
      labels:
        app: pickleman
        detail: pickleman
    spec:
      containers:
        - env:
            - name: CONFIG_VAL
            - value: pickel-man
          image: gcr.io/iot-001-205114/pickle-rick
          name: iot-001-205114-pickle-rick
          ports:
            - containerPort: 4444
      imagePullSecrets:
        - name: gcr
