apiVersion: v1
kind: Service
metadata:
  name: pickleman
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4444
  selector:
    name: pickle
  sessionAffinity: None
